import polars as pl
from typing import List

def union_candidates(candidate_dfs: List[pl.DataFrame]) -> pl.DataFrame:
    """
    Unions multiple candidate DataFrames.
    If a pair is generated by multiple channels, concatenates the channel names.
    """
    if not candidate_dfs:
        return pl.DataFrame()
        
    combined = pl.concat(candidate_dfs)
    
    # Group by the pair and aggregate the retrieval channels
    # Sort to ensure determinism
    aggregated = (
        combined.group_by(["source1_entity_id", "candidate_entity_id"])
        .agg(
            pl.col("retrieval_channels").unique().sort().str.join("|")
        )
    )
    
    return aggregated
